### ISSUE TITLE
Command md doesn't work

### ISSUE THREAD

**Issue by hendrixroa** [Gufran/terraform-docs#2]
First of all, very well tools, really looks awesome, I tested the last version of binaries section for mac 64 bits and getting some errors:

```
// I used the example 
./terraform-docs md main.tf
2019/04/26 20:14:55 stat md: no such file or directory
```

But i executed the cmd:

```
  // Without md
 ./terraform-docs main.tf
```
and return:

```
This documentation is automatically generated by `terraform-docs` utility.
Every sections below should have its own introductory paragraph, go ahead and read.



### Resources

| Type | Name |
|------|------|
| <div id='resource.aws_instance.app'></div> `aws_instance` | app |
| <div class='description'></div> Resources have description as well. | <div class='empty'></div> |
| <div id='resource.random_pet.suffix'></div> `random_pet` | suffix |
| <div class='description'></div> This description is associated with random_pet resource. | <div class='empty'></div> |



### Data Providers

Intro docs can appear in any order and in any file regardless of their
position in generated documentation. The order of comments in each file
is retained.


| Type | Name |
|------|------|
| <div id='data.aws_ami.app'></div> `aws_ami` | app |
| <div class='description'></div> This description is associated with aws_ami data provider and will appear in docs | <div class='empty'></div> |
| <div id='data.aws_iam_policy_document.allow_assume_role'></div> `aws_iam_policy_document` | allow_assume_role |
| <div class='description'></div> This IAM policy is allows an EC2 instance to assume roles | <div class='empty'></div> |
| <div id='data.aws_iam_policy_document.allow_describe_tags'></div> `aws_iam_policy_document` | allow_describe_tags |
| <div class='description'></div> This IAM policy allows describing all EC2 instances and their tags | <div class='empty'></div> |



### IAM Policies

##### allow_assume_role

!!! quote "allow_assume_role policy document"
    This IAM policy is allows an EC2 instance to assume roles
    
    ``` json
    {
      "statement" {
        actions = [
          "sts:AssumeRole",
        ]
    
        principals {
          type = "Service"
    
          identifiers = [
            "ec2.amazonaws.com",
          ]
        }
      }
    }
    ```
##### allow_describe_tags

!!! quote "allow_describe_tags policy document"
    This IAM policy allows describing all EC2 instances and their tags
    
    ``` json
    {
      "statement" {
        actions = [
          "ec2:DescribeInstances",
          "ec2:DescribeTags",
        ]
    
        resources = ["*"]
      }
    }
    ```

### Inputs

This is the intro paragraph of Input section.
Comment sections are separated by an uncommented empty line.

The commented empty line above means this line is part
of intro paragraph.

| Name | Description | Type |
|------|-------------|:----:|
| <div id='var.az'></div> az | This description is read from associated comment | list |
| <div id='var.version'></div> version | This description is read from attribute | string |

### Outputs

This is the intro paragraph for output section.
It will be displayed on top of outputs table.

| Name | Description |
|------|-------------|
| <div id='output.instance_id'></div> instance_id | This is the instance ID |

```

Other question, on the readme there is a .gif file with html and markdown syntax, how I can generate docs like the .gif ?

**Comment by Gufran** [comment]
Thanks for taking the time to file this issue.
The main purpose of this utility was to generate markdown documentation so I believe the other formats may have stopped working at some point and I didn't find out because I never needed those.
On the upside though, you don't need the `md` command if you want to generate markdown docs, as you've discovered the app will output markdown by default.
If you need to generate markdown then you don't need `md` command.

As for the GIF in readme file, that is [mkdocs material][] theme with slight customization. You can use the markdown files generated by this utility to generate an MkDocs static website.


[mkdocs material]: https://squidfunk.github.io/mkdocs-material/

**Comment by hendrixroa** [comment]
@Gufran  Thanks very much, all my questions are clarified. I'll use your tool a lot.
